baseURL = "http://example.org/"
languageCode = "de-de"
title = "Fotogilde Uelzen"
theme = "massively"
[languages]
[languages.en]
  languageName = "English"
 [[menu.main]]
    name = "Tanztitel"
    url = "/Tanztitel/"
    weight = 1
    
       


